by:
  group:
    project:
      xmlPath: src.main.resources.warehouse.xml
      intermediateXml: src.main.resources.intermediateXml.xml
      xsdPath: src.main.resources.warehouse_validator.xsd

server:
  port: 9090